/*
 * Pixel-art indexado del tablero de puente de madera de seven-bridges-walk
 * (Seven Bridges Visual Polish). Decoración nueva y puramente cosmética:
 * se coloca sobre tramos de agua ya transitables (las decoraciones nunca
 * alimentan solidTiles, ver WorldScene.js), dando lectura visual de
 * "cruce" donde antes solo había agua lisa. Una única variante, reutilizada
 * vía cache en los dos cruces del paseo -- orientación este-oeste, con
 * barandilla de hierro en ambos bordes largos.
 */

export const BRIDGE_TRANSPARENT = ".";

export const BRIDGE_PALETTE = {
  O: "#201d18", // contorno
  r: "#2b2b2e", // barandilla de hierro
  R: "#4a4a4d", // resalte de la barandilla
  d: "#3f2a1e", // junta oscura entre tablones
  W: "#7c5134", // madera media
  x: "#a06f4c", // resalte de madera
  s: "rgb(0 0 0 / 30%)", // sombra de contacto sobre el agua
};

export const BRIDGE_PIXEL_WIDTH = 96;
export const BRIDGE_PIXEL_HEIGHT = 48;

export const BRIDGE_PIXELS = [
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "rrrrOrrrrrrrrrrrOrrrrrrrrrrrOrrrrrrrrrrrOrrrrrrrrrrrOrrrrrrrrrrrOrrrrrrrrrrrOrrrrrrrrrrrOrrrrrrr",
  "RRRRORRRRRRRRRRRORRRRRRRRRRRORRRRRRRRRRRORRRRRRRRRRRORRRRRRRRRRRORRRRRRRRRRRORRRRRRRRRRRORRRRRRR",
  "....O...........O...........O...........O...........O...........O...........O...........O.......",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWWdWWWWWWWWWWW",
  "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
  "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
];
